# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BS' Page
email: bluesea.it@gmail.com
city: Ho Chi Minh city
country: Vietnam

description: > # this means to ignore newlines until "baseurl:"
  Tag: Hardware Design, C#WinForm, C#WPF, C#ASP.NET MVC, Robotics, IoT, High-tech Agriculture, House Control Automatic
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bs135.github.io" # the base hostname & protocol for your site
twitter_username: bsn135
github_username: bs135
facebook_username: bs135
skype_username: thanh_hai_135

footer_heading: About me
footer_name: BS Nguyen

# Build settings
markdown: kramdown

# Deloy
destination:  ../bs135.github.io